import type { Deck } from "@/lib/schema";

export const macroeconomicsDeck: Deck = {
  id: "macroeconomics-deck",
  courseId: "macroeconomics",
  cards: [
    {
      id: "macroeconomics-fc-y",
      topic: "gdp",
      tags: ["symbols"],
      front: "What does $y$ represent?",
      back: "Output, income, or GDP. In equilibrium problems it is the output level solved from IS and LM.",
    },
    {
      id: "macroeconomics-fc-disposable-income",
      topic: "gdp",
      tags: ["formula"],
      front: "Disposable income formula?",
      back: String.raw`$y^D=y-T+Tr=(1-t)y-T_0+Tr$.`,
    },
    {
      id: "macroeconomics-fc-tax",
      topic: "gdp",
      tags: ["formula"],
      front: "Total taxes?",
      back: String.raw`$T=T_0+t y$. Do not confuse lump-sum taxes $T_0$ with total taxes $T$.`,
    },
    {
      id: "macroeconomics-fc-budget-deficit",
      topic: "gdp",
      tags: ["formula", "sign"],
      front: "Budget deficit formula and sign convention?",
      back: String.raw`$BD=G-T+Tr+Sv$; usually $Sv=0$, so $BD=G-T+Tr$. Positive means deficit, negative means surplus.`,
    },
    {
      id: "macroeconomics-fc-alpha",
      topic: "multipliers",
      tags: ["formula"],
      front: "Closed-economy goods-market multiplier before IS-LM?",
      back: String.raw`$\alpha_G=\frac{1}{1-c(1-t)}$. Use it before investment becomes interest-sensitive.`,
    },
    {
      id: "macroeconomics-fc-tax-rate-change",
      topic: "multipliers",
      tags: ["formula", "trap"],
      front: "Tax-rate change multiplier logic?",
      back: String.raw`Use $\Delta y=\frac{-c\Delta t\cdot y_0}{1-c(1-t_1)}$ before IS-LM, or add $+bk/h$ (and $+m$ in open economy) in the denominator. Tax-rate changes alter the denominator.`,
    },
    {
      id: "macroeconomics-fc-investment",
      topic: "is-lm",
      tags: ["formula"],
      front: "Interest-sensitive investment?",
      back: String.raw`$I=I_0-br$. Higher $r$ lowers investment and gives IS its negative slope.`,
    },
    {
      id: "macroeconomics-fc-closed-is",
      topic: "is-lm",
      tags: ["formula"],
      front: "Closed-economy IS curve?",
      back: String.raw`$y=\frac{1}{1-c(1-t)}(C_0-cT_0+cTr+I_0+G-br)$.`,
    },
    {
      id: "macroeconomics-fc-lm",
      topic: "is-lm",
      tags: ["formula"],
      front: "LM curve?",
      back: String.raw`Money equilibrium: $\frac{M}{P}=ky-hr$. Solved for output: $y=\frac{1}{k}\frac{M}{P}+\frac{h}{k}r$.`,
    },
    {
      id: "macroeconomics-fc-islm-equilibrium",
      topic: "is-lm",
      tags: ["formula"],
      front: "Closed-economy IS-LM equilibrium output?",
      back: String.raw`$y^*=\frac{C_0-cT_0+cTr+I_0+G+\frac{b}{h}\frac{M}{P}}{1-c(1-t)+\frac{bk}{h}}$.`,
    },
    {
      id: "macroeconomics-fc-islm-r",
      topic: "is-lm",
      tags: ["formula"],
      front: "How do you recover $r^*$ after finding $y^*$?",
      back: String.raw`Use the LM equation: $r^*=\frac{k}{h}y^*-\frac{1}{h}\frac{M}{P}$.`,
    },
    {
      id: "macroeconomics-fc-islm-multipliers",
      topic: "is-lm-policy",
      tags: ["formula"],
      front: "IS-LM fiscal and monetary multipliers?",
      back: String.raw`$\Gamma_G=\frac{1}{1-c(1-t)+\frac{bk}{h}}$ and $\Gamma_M=\Gamma_G\frac{b}{h}$.`,
    },
    {
      id: "macroeconomics-fc-fiscal-shock",
      topic: "curve-shifts",
      tags: ["policy", "sign"],
      front: "Fiscal expansion in IS-LM: curve shift and signs?",
      back: "IS shifts right; output rises; the interest rate rises; investment is partly crowded out.",
    },
    {
      id: "macroeconomics-fc-monetary-shock",
      topic: "curve-shifts",
      tags: ["policy", "sign"],
      front: "Monetary expansion in IS-LM: curve shift and signs?",
      back: "LM shifts right/down; output rises; the interest rate usually falls.",
    },
    {
      id: "macroeconomics-fc-nx",
      topic: "open-economy",
      tags: ["formula"],
      front: "Net exports in the basic open-economy model?",
      back: String.raw`$NX=NX_0-my$. Higher domestic output raises imports, so $NX$ falls.`,
    },
    {
      id: "macroeconomics-fc-cf",
      topic: "open-economy",
      tags: ["formula", "sign"],
      front: "Capital-flow convention in this course?",
      back: String.raw`$CF=nr$ is net capital outflow. A negative $CF$ means net capital inflow.`,
    },
    {
      id: "macroeconomics-fc-bp",
      topic: "bp-curve",
      tags: ["formula", "sign"],
      front: "Balance-of-payments definition and external balance?",
      back: String.raw`$BP=NX-CF$. External balance is $BP=0$, which means $NX=CF$.`,
    },
    {
      id: "macroeconomics-fc-bp-curve",
      topic: "bp-curve",
      tags: ["formula"],
      front: "BP curve when $CF=nr$?",
      back: String.raw`From $NX_0-my=nr$: $y=\frac{NX_0}{m}-\frac{n}{m}r$.`,
    },
    {
      id: "macroeconomics-fc-zero-mobility",
      topic: "bp-curve",
      tags: ["case"],
      front: "What does zero capital mobility do to BP?",
      back: String.raw`If $n=0$, then $y=NX_0/m$. The BP curve is vertical.`,
    },
    {
      id: "macroeconomics-fc-perfect-mobility",
      topic: "bp-curve",
      tags: ["case"],
      front: "What does perfect capital mobility do to BP?",
      back: String.raw`BP is horizontal at the world interest rate $r_f$.`,
    },
    {
      id: "macroeconomics-fc-open-is",
      topic: "is-lm-bp",
      tags: ["formula"],
      front: "Open-economy IS curve?",
      back: String.raw`$y=\frac{1}{1-c(1-t)+m}(C_0-cT_0+cTr+I_0+G+NX_0-br)$.`,
    },
    {
      id: "macroeconomics-fc-islmbp-equilibrium",
      topic: "is-lm-bp",
      tags: ["formula"],
      front: "Open-economy IS-LM internal equilibrium output?",
      back: String.raw`$y^*=\frac{C_0-cT_0+cTr+I_0+G+NX_0+\frac{b}{h}\frac{M}{P}}{1-c(1-t)+m+\frac{bk}{h}}$.`,
    },
    {
      id: "macroeconomics-fc-open-multipliers",
      topic: "is-lm-bp",
      tags: ["formula"],
      front: "Open-economy fiscal and monetary multipliers?",
      back: String.raw`$\Gamma_G=\frac{1}{1-c(1-t)+m+\frac{bk}{h}}$ and $\Gamma_M=\Gamma_G\frac{b}{h}$. Imports reduce the fiscal multiplier.`,
    },
    {
      id: "macroeconomics-fc-internal-external",
      topic: "is-lm-bp",
      tags: ["trap"],
      front: "In IS-LM-BP, why is $IS=LM$ not enough?",
      back: String.raw`$IS=LM$ gives internal equilibrium. You still compute $NX$, $CF$, and $BP=NX-CF$ to check external balance.`,
    },
  ],
};
