import type { QuestionBank } from "@/lib/schema";

export const macroeconomicsBank: QuestionBank = {
  id: "macroeconomics-bank",
  courseId: "macroeconomics",
  questions: [
    {
      id: "macroeconomics-q-is-tax-autonomous",
      type: "mcq",
      topic: "curve-shifts",
      difficulty: "medium",
      prompt: "In an IS-LM model, an increase in autonomous taxes $T_0$ makes:",
      options: ["IS shift to the right", "IS rotate to the left", "LM shift to the left", "IS shift to the left"],
      answer: "IS shift to the left",
      answerConfidence: "confirmed",
      explanation: String.raw`Higher $T_0$ lowers disposable income and consumption at each interest rate, so goods-market demand falls and IS shifts left. This source item used "none of the above" because the original listed options did not include "IS shifts left".`,
      source: "Quantitative Macroeconomics 14. Exam.md Q2",
    },
    {
      id: "macroeconomics-q-g-cut-multiplier",
      type: "mcq",
      topic: "multipliers",
      difficulty: "medium",
      prompt: String.raw`In a closed economy with $c=0.9$ and $t=0.3$, a decrease in government spending by 10 changes GDP by about:`,
      options: ["-27", "27", "-50", "50"],
      answer: "-27",
      answerConfidence: "confirmed",
      explanation: String.raw`$\alpha_G=1/(1-0.9(1-0.3))=1/0.37\approx2.7$, so $\Delta y=2.7(-10)\approx-27$.`,
      source: "Quantitative Macroeconomics 14. Exam.md Q3",
    },
    {
      id: "macroeconomics-q-multiplier-ranking",
      type: "mcq",
      topic: "is-lm-policy",
      difficulty: "hard",
      prompt: String.raw`In an IS-LM model with $c=0.75$, $t=0.2$, $b=1000$, $k=0.3$, and $h=500$, which relation is correct?`,
      options: [
        String.raw`$\Gamma_M>\Gamma_G>\alpha_G$`,
        String.raw`$\Gamma_M>\alpha_G>\Gamma_G$`,
        String.raw`$\alpha_G>\Gamma_G>\Gamma_M$`,
        String.raw`$\alpha_G>\Gamma_M>\Gamma_G$`,
      ],
      answer: String.raw`$\alpha_G>\Gamma_M>\Gamma_G$`,
      answerConfidence: "confirmed",
      explanation: String.raw`$\alpha_G=1/(1-0.75(0.8))=2.5$. $\Gamma_G=1/(1-0.75(0.8)+1000(0.3)/500)=1$. $\Gamma_M=\Gamma_G(b/h)=2$.`,
      source: "Quantitative Macroeconomics 14. Exam.md Q8",
    },
    {
      id: "macroeconomics-q-bp-definition",
      type: "mcq",
      topic: "bp-curve",
      difficulty: "easy",
      prompt: "Using this course's convention, external equilibrium means:",
      options: ["BD=0", "NX=CF", "G=T", "IS=LM"],
      answer: "NX=CF",
      answerConfidence: "confirmed",
      explanation: String.raw`The course convention is $BP=NX-CF$. External balance is $BP=0$, therefore $NX=CF$.`,
      source: "is-lm-bp-course/06-open-economy-bp.md",
    },
    {
      id: "macroeconomics-q-bp-zero-mobility",
      type: "mcq",
      topic: "bp-curve",
      difficulty: "medium",
      prompt: String.raw`If $NX_0=530$, $m=0.1$, and $n=0$, the BP curve is:`,
      options: ["horizontal at r=0.1", "vertical at y=5300", "downward with slope -53", "upward with slope 0.1"],
      answer: "vertical at y=5300",
      answerConfidence: "confirmed",
      explanation: String.raw`With $n=0$, $NX_0-my=0$, so $y=NX_0/m=530/0.1=5300$.`,
      source: "is-lm-bp-course/08-is-lm-bp-policy-lab.md",
    },
    {
      id: "macroeconomics-q-nx-output",
      type: "mcq",
      topic: "open-economy",
      difficulty: "easy",
      prompt: "If domestic output rises and everything else is unchanged, what happens to net exports in the model $NX=NX_0-my$?",
      options: ["NX rises", "NX falls", "NX is unchanged", "NX equals CF automatically"],
      answer: "NX falls",
      answerConfidence: "confirmed",
      explanation: "Higher domestic output raises imports, so net exports fall.",
      source: "is-lm-bp-course/06-open-economy-bp.md",
    },
    {
      id: "macroeconomics-q-lm-slope",
      type: "mcq",
      topic: "is-lm",
      difficulty: "easy",
      prompt: String.raw`From money-market equilibrium $\frac{M}{P}=ky-hr$, the LM curve solved for output is:`,
      options: [
        String.raw`$y=\frac{1}{k}\frac{M}{P}+\frac{h}{k}r$`,
        String.raw`$y=\frac{1}{h}\frac{M}{P}+\frac{k}{h}r$`,
        String.raw`$y=\frac{M}{P}-kr$`,
        String.raw`$y=C+I+G$`,
      ],
      answer: String.raw`$y=\frac{1}{k}\frac{M}{P}+\frac{h}{k}r$`,
      answerConfidence: "confirmed",
      explanation: String.raw`Rearrange $M/P=ky-hr$ into $ky=M/P+hr$, then divide by $k$.`,
      source: "is-lm-bp-course/03-is-lm-core.md",
    },
    {
      id: "macroeconomics-q-is-slope",
      type: "mcq",
      topic: "is-lm",
      difficulty: "easy",
      prompt: "Why does the IS curve slope downward?",
      options: [
        "Higher output raises money demand",
        "Higher interest rates lower investment and aggregate demand",
        "Higher taxes raise government spending",
        "Higher imports raise net exports",
      ],
      answer: "Higher interest rates lower investment and aggregate demand",
      answerConfidence: "confirmed",
      explanation: String.raw`Because $I=I_0-br$, a higher $r$ lowers investment and the goods-market output consistent with equilibrium.`,
      source: "is-lm-bp-course/03-is-lm-core.md",
    },
    {
      id: "macroeconomics-q-monetary-expansion-signs",
      type: "mcq",
      topic: "policy-shocks",
      difficulty: "medium",
      prompt: "In the standard IS-LM model, a monetary expansion usually:",
      options: [
        "shifts IS right, raises output, raises r",
        "shifts LM right/down, raises output, lowers r",
        "shifts LM left/up, lowers output, raises r",
        "rotates BP and leaves IS-LM unchanged",
      ],
      answer: "shifts LM right/down, raises output, lowers r",
      answerConfidence: "confirmed",
      explanation: String.raw`Higher $M/P$ shifts LM right/down. Output rises and $r$ falls through $\Delta r=(k/h)\Delta y-(1/h)\Delta(M/P)$.`,
      source: "is-lm-bp-course/04-is-lm-policy.md",
    },
    {
      id: "macroeconomics-q-gamma-vs-alpha",
      type: "mcq",
      topic: "is-lm-policy",
      difficulty: "medium",
      prompt: String.raw`Why is the IS-LM fiscal multiplier $\Gamma_G$ usually smaller than the goods-market multiplier $\alpha_G$?`,
      options: [
        "Because taxes disappear in IS-LM",
        "Because imports are always zero",
        "Because monetary crowding out adds the term bk/h to the denominator",
        "Because LM shifts left after every fiscal expansion",
      ],
      answer: "Because monetary crowding out adds the term bk/h to the denominator",
      answerConfidence: "confirmed",
      explanation: String.raw`$\Gamma_G=1/(1-c(1-t)+bk/h)$, while $\alpha_G=1/(1-c(1-t))$. The positive $bk/h$ term increases the denominator.`,
      source: "is-lm-bp-course/04-is-lm-policy.md",
    },
    {
      id: "macroeconomics-q-import-leakage",
      type: "mcq",
      topic: "is-lm-bp",
      difficulty: "medium",
      prompt: "Why does adding imports weaken the open-economy multiplier?",
      options: [
        "The import term m is added to the multiplier denominator",
        "Imports make LM horizontal",
        "Imports remove taxes from the model",
        "Imports force BP to equal BD",
      ],
      answer: "The import term m is added to the multiplier denominator",
      answerConfidence: "confirmed",
      explanation: String.raw`Open-economy $\Gamma_G=1/(1-c(1-t)+m+bk/h)$. A larger $m$ means more demand leaks into imports, so output responds less.`,
      source: "is-lm-bp-course/07-is-lm-bp-core.md",
    },
    {
      id: "macroeconomics-q-negative-cf",
      type: "mcq",
      topic: "open-economy",
      difficulty: "medium",
      prompt: String.raw`Under the course convention, what does a negative $CF$ mean?`,
      options: ["Net capital outflow", "Net capital inflow", "Budget deficit", "Trade surplus"],
      answer: "Net capital inflow",
      answerConfidence: "confirmed",
      explanation: "The package defines CF as net capital outflow. A negative outflow is an inflow.",
      source: "is-lm-bp-course/06-open-economy-bp.md",
    },
    {
      id: "macroeconomics-q-bd-sign",
      type: "mcq",
      topic: "gdp",
      difficulty: "easy",
      prompt: String.raw`If $G=500$, $T=650$, and $Tr=0$, then $BD$ is:`,
      options: ["150 deficit", "150 surplus", "1150 deficit", "0 balanced"],
      answer: "150 surplus",
      answerConfidence: "confirmed",
      explanation: String.raw`$BD=G-T+Tr=500-650=-150$. Negative BD means a surplus of 150.`,
      source: "is-lm-bp-course/01-foundations.md",
    },
    {
      id: "macroeconomics-q-capstone-is",
      type: "mcq",
      topic: "is-lm-bp",
      difficulty: "hard",
      prompt: String.raw`For the capstone economy, the numerical IS curve is:`,
      options: ["y=2600-400r", "y=1600+1600r", "y=2187.5", "y=2400+500r"],
      answer: "y=2600-400r",
      answerConfidence: "confirmed",
      explanation: String.raw`Substituting the capstone values into open-economy IS gives $y=2600-400r$.`,
      source: "is-lm-bp-course/09-capstone-review.md",
    },
    {
      id: "macroeconomics-q-capstone-equilibrium",
      type: "mcq",
      topic: "is-lm-bp",
      difficulty: "hard",
      prompt: String.raw`For the capstone economy with $IS: y=2600-400r$ and $LM: y=1600+1600r$, the internal equilibrium is:`,
      options: ["y=2400, r=50%", "y=2187.5, r=0", "y=2600, r=0", "y=1600, r=50%"],
      answer: "y=2400, r=50%",
      answerConfidence: "confirmed",
      explanation: String.raw`Set $2600-400r=1600+1600r$. Then $r=0.5$ and $y=2400$.`,
      source: "is-lm-bp-course/answers/answer-key-09.md",
    },
  ],
};
