import type { Deck } from "@/lib/schema";

/**
 * Management flashcard deck — the memorizable layer (definitions, fixed lists,
 * formulas, classifications). Converted 1:1 from materials/management/flashcards.md
 * (65 starter cards), English-only, each tagged by topic.
 *
 * `topic` is the course's primary tag (used by the SRS / progress views); `tags`
 * carry the sub-topic and any mnemonic hook from the source card header.
 * `[VOLATILE]` Romanian tax/legal figures are flagged in the card body.
 */
export const managementDeck: Deck = {
  id: "management-deck",
  courseId: "management",
  cards: [
    // ---- LU1 — Theoretical Foundations -------------------------------------
    {
      id: "management-fc-1",
      topic: "foundations",
      tags: ["meanings", "mnemonic:SAD-PD"],
      front: "The five meanings of “management”?",
      back: "science · art · discipline of study · practical activity · decision center. Hint: “SAD-PD”.",
    },
    {
      id: "management-fc-2",
      topic: "foundations",
      tags: ["meanings", "reverse"],
      front: "Management **as a science** is…?",
      back: "the study of management processes within organizations **of any kind**, to discover/perfect concepts, rules, systems, methods, techniques.",
    },
    {
      id: "management-fc-3",
      topic: "foundations",
      tags: ["meanings", "reverse"],
      front: "Management **as a practical activity** is…?",
      back: "carrying out the management process — allocating & using the organization's resources so objectives are met under **effectiveness and efficiency**.",
    },
    {
      id: "management-fc-4",
      topic: "foundations",
      tags: ["functions", "mnemonic:Plan-Organize-3Cs"],
      front: "The five management functions, in order (Fayol)?",
      back: "Planning · Organizing · Coordinating · Commanding · Controlling. Hint: “Plan, Organize, then 3 C's.”",
    },
    {
      id: "management-fc-5",
      topic: "foundations",
      tags: ["functions"],
      front: "The **organizing** function?",
      back: "determining the work processes needed for the objectives and assigning them to organizational components (divisions, departments, offices, workplaces).",
    },
    {
      id: "management-fc-6",
      topic: "foundations",
      tags: ["functions"],
      front: "The **controlling** function's four stages?",
      back: "(1) assess results → (2) compare to objectives → (3) determine deviations → (4) corrective measures (remove negatives, generalize positives).",
    },
    {
      id: "management-fc-7",
      topic: "foundations",
      tags: ["functions", "cloze"],
      front: "The support of **coordinating** is ___; the basis of **commanding** is ___.",
      back: "communication; motivation.",
    },
    {
      id: "management-fc-8",
      topic: "foundations",
      tags: ["schools"],
      front: "The four schools of management + one representative each?",
      back: "Classical (Taylor/Fayol) · Human Relations (Mayo/Maslow) · Quantitative (Deming/Juran) · Systemic (Drucker/Porter/Goldratt).",
    },
    {
      id: "management-fc-9",
      topic: "foundations",
      tags: ["managers", "reverse"],
      front: "A **manager** is…?",
      back: "an individual who exercises the management functions based on **formal authority** invested upon them.",
    },
    {
      id: "management-fc-10",
      topic: "foundations",
      tags: ["managers"],
      front: "The three manager levels + key trait of each?",
      back: "low (only ones who don't subordinate other managers) · middle (subordinate low, report to top; indirect employee relations) · top (set philosophy, strategic planning, whole-org decisions).",
    },
    {
      id: "management-fc-11",
      topic: "foundations",
      tags: ["environment", "classify"],
      front: "Clients, competitors, suppliers, labor market = which environment?",
      back: "the **micro-environment** (direct influence). Macro = technological/socio-cultural/economic/political/legal/natural (indirect). Internal = owners/managers/employees/culture.",
    },
    {
      id: "management-fc-12",
      topic: "foundations",
      tags: ["organization"],
      front: "Difference between an **organization** and a **company**?",
      back: "organization = ≥2 people for a common goal; company = ≥2 people selling products/services/works **for profit**.",
    },

    // ---- LU2 — The Management Decision --------------------------------------
    {
      id: "management-fc-13",
      topic: "decision",
      tags: ["decision", "reverse"],
      front: "The **management decision** is…?",
      back: "a rational process of choosing an alternative from several, **influencing the actions of ≥1 other person**, to reach one/several objectives under **maximum efficiency**.",
    },
    {
      id: "management-fc-14",
      topic: "decision",
      tags: ["primary-factors"],
      front: "The two **primary factors** of the decision?",
      back: "the decision-maker · the environment.",
    },
    {
      id: "management-fc-15",
      topic: "decision",
      tags: ["requirements"],
      front: "The requirements for an efficient decision?",
      back: "scientifically founded · adopted by legally empowered persons · clear & concise · correlated with other decisions · opportune (timely) · efficient.",
    },
    {
      id: "management-fc-16",
      topic: "decision",
      tags: ["requirements", "cloze"],
      front: "“Scientifically founded” means using scientific methods, considering economic laws, properly using data processing, and eliminating ___, ___, and ___.",
      back: "routine · subjectivism · improvisation.",
    },
    {
      id: "management-fc-17",
      topic: "decision",
      tags: ["classification"],
      front: "The 8 decision classification criteria?",
      back: "time horizon · environment knowledge · management level · scope · frequency · anticipation · competence · number of criteria.",
    },
    {
      id: "management-fc-18",
      topic: "decision",
      tags: ["classification", "classify"],
      front: "By **time horizon**, decisions are…?",
      back: "strategic · tactical · operational.",
    },
    {
      id: "management-fc-19",
      topic: "decision",
      tags: ["methods", "certainty"],
      front: "Two multi-criteria methods under **certainty**?",
      back: "Global Utility · ELECTRE.",
    },
    {
      id: "management-fc-20",
      topic: "decision",
      tags: ["uncertainty", "mnemonic:POHLS"],
      front: "The five **uncertainty** decision rules?",
      back: "Pessimistic (Wald) · Optimistic · Hurwicz · Laplace · Savage (minimax regret). Hint: “POHLS”.",
    },
    {
      id: "management-fc-21",
      topic: "decision",
      tags: ["risk", "formula"],
      front: "Decision criterion under **risk**?",
      back: "**mathematical expectancy** ME_i = Σ(p_j × a_ij); pick the most favorable (used for repetitive decisions).",
    },
    {
      id: "management-fc-22",
      topic: "calc-toc",
      tags: ["TOC", "methods"],
      front: "Theory of Constraints — the 5 steps?",
      back: "identify the bottleneck → exploit it → subordinate the rest → elevate/improve it → repeat. Prioritise the product with highest **output per bottleneck-minute**.",
    },

    // ---- LU3 — Strategic Management -----------------------------------------
    {
      id: "management-fc-23",
      topic: "strategy",
      tags: ["strategy", "mnemonic:VMOMRDC"],
      front: "The 7 components of strategy, in order?",
      back: "Vision · Mission · Strategic objectives · Strategic means of action · Resources · Deadlines · Competitive advantage. Hint: “Very Many Old Managers Really Dislike Competition.”",
    },
    {
      id: "management-fc-24",
      topic: "strategy",
      tags: ["strategy"],
      front: "Vision vs Mission?",
      back: "Vision = where the org must go (product/target/purpose). Mission = adds the **source of competitive advantage** / why customers prefer us (marketable wording).",
    },
    {
      id: "management-fc-25",
      topic: "strategy",
      tags: ["competitive-advantage", "cloze"],
      front: "Per Porter, competitive advantage is either ___ or ___.",
      back: "lower cost · differentiation.",
    },
    {
      id: "management-fc-26",
      topic: "strategy",
      tags: ["KSF", "reverse"],
      front: "**Key Success Factors (KSF)** are…?",
      back: "the elements based on which an organization engages in competitive struggle (competences/assets giving competitive advantage).",
    },
    {
      id: "management-fc-27",
      topic: "strategy",
      tags: ["SAS"],
      front: "A **Strategic Activity Segment (SAS)**?",
      back: "product lines made with the same technology & resources, facing the same competition on the same market, with the same KSF.",
    },
    {
      id: "management-fc-28",
      topic: "strategy",
      tags: ["SWOT"],
      front: "The four SWOT quadrant strategies?",
      back: "SO → grow/develop · WO → seize opportunities to fix weaknesses · ST → build barriers using strengths · WT → exit the non-performing segment.",
    },
    {
      id: "management-fc-29",
      topic: "strategy",
      tags: ["porter"],
      front: "Porter's five forces?",
      back: "rivalry among competitors · threat of new entrants · substitutes · customer bargaining power · supplier bargaining power.",
    },
    {
      id: "management-fc-30",
      topic: "strategy",
      tags: ["porter", "entry-barriers"],
      front: "The six categories of entry barriers?",
      back: "transfer costs · experience effect · access to distribution networks · production-capacity reserves · capital need · government policy/regulations.",
    },
    {
      id: "management-fc-31",
      topic: "strategy",
      tags: ["SWOT", "classify"],
      front: "“Changes in consumer preferences” is which SWOT element?",
      back: "external & uncontrollable → an **opportunity or a threat** (not a strength/weakness).",
    },

    // ---- LU4 — The Management System ----------------------------------------
    {
      id: "management-fc-32",
      topic: "mgmt-system",
      tags: ["system"],
      front: "The four subsystems of the management system?",
      back: "decision-making · informational · organizational · methodological.",
    },
    {
      id: "management-fc-33",
      topic: "mgmt-system",
      tags: ["compartments", "classify"],
      front: "Functional vs operational compartment?",
      back: "functional = support core activities (Quality, Financial); operational = directly achieve the org's purpose (production).",
    },
    {
      id: "management-fc-34",
      topic: "mgmt-system",
      tags: ["job"],
      front: "The four components of a **job**?",
      back: "objectives · tasks · authority · responsibilities.",
    },
    {
      id: "management-fc-35",
      topic: "mgmt-system",
      tags: ["span", "reverse"],
      front: "**Span of control** = ? Recommended range?",
      back: "the number of jobs **directly subordinated** to a manager; recommended **5–10**.",
    },
    {
      id: "management-fc-36",
      topic: "mgmt-system",
      tags: ["relations"],
      front: "The three organizational relation types?",
      back: "authority (hierarchical/functional/matrix) · cooperation · control.",
    },
    {
      id: "management-fc-37",
      topic: "mgmt-system",
      tags: ["formalizing", "cloze"],
      front: "Main formalizing document — structural org = ___; processual org = ___.",
      back: "organizational chart · procedure.",
    },
    {
      id: "management-fc-38",
      topic: "mgmt-system",
      tags: ["SMART"],
      front: "SMART stands for…?",
      back: "Specific · Measurable · Achievable · Relevant · Time-bound.",
    },
    {
      id: "management-fc-39",
      topic: "mgmt-system",
      tags: ["objectives", "mnemonic:F-1-2-S-I"],
      front: "The 5 levels of the system of objectives (top→bottom)?",
      back: "fundamental → 1st-degree main → 2nd-degree main → specific → individual. (Strategic objectives sit here as **fundamental**.)",
    },
    {
      id: "management-fc-40",
      topic: "mgmt-system",
      tags: ["objectives", "classify"],
      front: "“Increase net profit by 10% next year” — which objective category?",
      back: "**fundamental** (long-term, whole-org) — NOT specific (specific = operational, days/weeks/months).",
    },

    // ---- LU5 — Project Management -------------------------------------------
    {
      id: "management-fc-41",
      topic: "projects",
      tags: ["project", "reverse"],
      front: "A **project** (PMI) is…?",
      back: "a temporary effort undertaken to create a product, service or **unique** result.",
    },
    {
      id: "management-fc-42",
      topic: "projects",
      tags: ["project"],
      front: "The four defining characteristics of a project?",
      back: "well-defined time frame · clearly defined objectives · allocated resources · uniqueness.",
    },
    {
      id: "management-fc-43",
      topic: "projects",
      tags: ["lifecycle", "mnemonic:Can-People-Execute-Cool-Tasks"],
      front: "The five life-cycle stages?",
      back: "conception · planning · execution · control · termination.",
    },
    {
      id: "management-fc-44",
      topic: "projects",
      tags: ["success"],
      front: "The three project success criteria?",
      back: "time · budget · quality.",
    },
    {
      id: "management-fc-45",
      topic: "projects",
      tags: ["WBS", "cloze"],
      front: "WBS rules: the ___% rule and the ___/___ rule (work-package hours).",
      back: "100% rule · 8/80 (8–80 hours per work package).",
    },
    {
      id: "management-fc-46",
      topic: "projects",
      tags: ["network"],
      front: "CPM vs PERT?",
      back: "CPM = **deterministic** single durations (focus on time reserves); PERT = **probabilistic** three-estimate durations.",
    },
    {
      id: "management-fc-47",
      topic: "calc-pert",
      tags: ["PERT", "formula"],
      front: "PERT estimated duration and σ?",
      back: "te = (P + 4M + O)/6 ; σ = (P − O)/6. (±1σ→68%, ±2σ→95%, ±3σ→99.7%.)",
    },
    {
      id: "management-fc-48",
      topic: "projects",
      tags: ["critical-path", "cloze"],
      front: "An activity is **critical** when its slack = ___ . Slack = ___ − EF.",
      back: "0 ; LF.",
    },
    {
      id: "management-fc-49",
      topic: "calc-npv",
      tags: ["NPV", "formula"],
      front: "NPV decision rule + discount factor?",
      back: "undertake if **NPV > 0**; discount factor = 1/(1+Rr+Ri)^t.",
    },
    {
      id: "management-fc-50",
      topic: "projects",
      tags: ["earned-value"],
      front: "Earned value: CV, SV, CPI, SPI?",
      back: "CV = BCWP − ACWP · SV = BCWP − BCWS · CPI = BCWP/ACWP · SPI = BCWP/BCWS (≥0 or ≥1 = good).",
    },

    // ---- LU6 — Human Resources Management -----------------------------------
    {
      id: "management-fc-51",
      topic: "hr",
      tags: ["recruitment", "reverse"],
      front: "**Recruitment** is…?",
      back: "identifying qualified-candidate sources and convincing them to apply for new or vacant jobs. (Selection = choosing among applicants.)",
    },
    {
      id: "management-fc-52",
      topic: "hr",
      tags: ["selection"],
      front: "The most common selection method?",
      back: "the **interview** (also the most criticized).",
    },
    {
      id: "management-fc-53",
      topic: "hr",
      tags: ["motivation", "mnemonic:My-Hamster-Always-Makes-Amends"],
      front: "The five motivation theories?",
      back: "Maslow (pyramid) · Herzberg (two-factor) · Alderfer (ERG) · McClelland (nAch/nAff/nPow) · Adams (equity).",
    },
    {
      id: "management-fc-54",
      topic: "hr",
      tags: ["motivation", "classify"],
      front: "Herzberg: are salary & job security motivators or hygiene factors?",
      back: "**hygiene** (extrinsic) — they prevent dissatisfaction but don't motivate. Motivators = work itself, responsibility, recognition.",
    },
    {
      id: "management-fc-55",
      topic: "hr",
      tags: ["maslow"],
      front: "Maslow's 5 needs (bottom→top)?",
      back: "physiological · safety/security · social · esteem · self-actualization.",
    },
    {
      id: "management-fc-56",
      topic: "hr",
      tags: ["teams", "tuckman"],
      front: "Tuckman's 5 team-development stages?",
      back: "forming · storming · norming · performing · adjourning.",
    },
    {
      id: "management-fc-57",
      topic: "hr",
      tags: ["conflict"],
      front: "The 5 conflict-handling styles + their win/lose label?",
      back: "accommodating · avoiding · collaborating (win-win) · competing (win-lose) · compromising (lose-lose).",
    },
    {
      id: "management-fc-58",
      topic: "hr",
      tags: ["communication"],
      front: "The five elements of communication?",
      back: "emitter · receiver · message · channel · feedback.",
    },

    // ---- LU7 — Entrepreneurship ---------------------------------------------
    {
      id: "management-fc-59",
      topic: "calc-sme",
      tags: ["SME", "volatile"],
      front: "SME definition + thresholds?",
      back: "**< 250** employees AND (turnover **≤ €50M** OR assets **≤ €43M**). Micro <10/€2M/€2M; Small <50/€10M/€43M. [VOLATILE]",
    },
    {
      id: "management-fc-60",
      topic: "entrepreneurship",
      tags: ["VAT", "volatile"],
      front: "What is VAT, and the current standard rate?",
      back: "an indirect tax on goods/services value, paid to the State Budget, borne by the final consumer; standard **21%** (reduced 11%). [VOLATILE]",
    },
    {
      id: "management-fc-61",
      topic: "calc-vat",
      tags: ["VAT", "formula"],
      front: "VAT value from the **final price** F (rate r)?",
      back: "V = F/(1+r) × r.  (NOT F × r — that's the classic trap.)",
    },
    {
      id: "management-fc-62",
      topic: "calc-salary",
      tags: ["salary", "formula", "volatile"],
      front: "Gross vs net vs **complete** salary?",
      back: "gross = pre-deduction pay; net = after CAS 25% + CASS 10% + income tax 10%; **complete = gross + CAM 2.25%** (employer cost). [VOLATILE]",
    },
    {
      id: "management-fc-63",
      topic: "calc-depreciation",
      tags: ["depreciation", "cloze", "volatile"],
      front: "Fiscally, an asset must be depreciated when its entry value is ≥ ___ RON.",
      back: "2,500 RON (and useful life > 1 year). Below that → working-inventory item (expensed at once). [VOLATILE]",
    },
    {
      id: "management-fc-64",
      topic: "entrepreneurship",
      tags: ["registration"],
      front: "The three enterprise-registration phases?",
      back: "pre-registration · registration · authorization of operation (ends with operating **license** [catering] or **agreement** [trade/services]).",
    },
    {
      id: "management-fc-65",
      topic: "entrepreneurship",
      tags: ["registration", "legal-forms"],
      front: "Romanian legal forms?",
      back: "PFA · II · SRL · SA · SNC · SCS · SCA · Societate Cooperativă.",
    },
  ],
};
