import type { QuestionBank } from "@/lib/schema";

/**
 * Management question bank. Three sources, all from materials/management/:
 *  • Q1–Q33  — the 33 past-exam items (test.md), keyed from reference §4.
 *  • PQ1–PQ18 — new practice items in the exam style (practice_questions.md §A/B).
 *  • CALC*    — worked numeric drills rendered as single-answer items (§C).
 *
 * `type`: "mcq" = one correct answer; "multi" = one-or-more-correct (graded as an
 * exact-set match, mirroring the real exam). `answer` strings/array members must
 * match the corresponding `options` verbatim. `answerConfidence: "confirmed"` is
 * used only where the key is certain; the three interpretive past items (Q26,
 * Q27, Q31, flagged in reference §4/§7C) carry "likely"/"attempt-selected".
 * `[VOLATILE]` Romanian tax figures (VAT 21%, CAM 2.25%, etc.) noted inline.
 */
export const managementBank: QuestionBank = {
  id: "management-bank",
  courseId: "management",
  questions: [
    // ===== Past exam items (test.md / reference §4) =========================
    {
      id: "management-q-1",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt: "The managerial decision represents:",
      options: [
        "a rational process of choosing one alternative of action from several possible ones, which influences the actions of at least one other person within the organization, in order to achieve one or more objectives under conditions of maximum efficiency",
        "the rational process of comparing multiple decisional alternatives based on economic criteria and choosing the most efficient one",
        "the conscious and rational choice made by a manager based on carefully chosen criteria, for maximum efficiency and effectiveness",
        "the conscious choice made following the examination of a problem, under conditions of maximum efficiency",
        "the process of choosing an alternative from several possible ones in order to achieve an objective under conditions of maximum efficiency",
      ],
      answer:
        "a rational process of choosing one alternative of action from several possible ones, which influences the actions of at least one other person within the organization, in order to achieve one or more objectives under conditions of maximum efficiency",
      answerConfidence: "confirmed",
      explanation:
        "Matches the LU2 definition verbatim. The discriminating phrase is **“influences the actions of at least one other person”** — every distractor drops it or narrows the scope (e.g. “economic criteria only”).",
      source: "Past exam Q1",
    },
    {
      id: "management-q-2",
      type: "mcq",
      topic: "foundations",
      difficulty: "easy",
      prompt:
        "Establishing the work processes needed to fulfil objectives and delimiting them at organizational components (department, service, office, workplace) represents:",
      options: ["forecasting", "organizing", "coordinating", "leading / motivating", "controlling"],
      answer: "organizing",
      answerConfidence: "confirmed",
      explanation: "Textbook wording of the **organizing** function (Fayol's 5 functions).",
      source: "Past exam Q2",
    },
    {
      id: "management-q-3",
      type: "mcq",
      topic: "projects",
      difficulty: "medium",
      prompt: "The criteria by which the success of a project is judged include:",
      options: ["profitability rate", "profit", "time", "production", "net present value"],
      answer: "time",
      answerConfidence: "confirmed",
      explanation:
        "Project success = the triple constraint **time / budget / quality**; only **time** appears among the options.",
      source: "Past exam Q3",
    },
    {
      id: "management-q-4",
      type: "mcq",
      topic: "hr",
      difficulty: "medium",
      prompt:
        "Identifying sources of qualified candidates and determining them to apply for new or vacant positions is called:",
      options: ["human resources management", "motivation", "selection", "recruitment", "pre-selection"],
      answer: "recruitment",
      answerConfidence: "confirmed",
      explanation:
        "Verbatim recruitment definition. **Selection** = choosing among the applicants (it comes after recruitment).",
      source: "Past exam Q4",
    },
    {
      id: "management-q-5",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "Strategic objectives are found within the categorical system of objectives as:",
      options: [
        "fundamental objectives",
        "derivative objectives of the first degree",
        "derivative objectives of the second degree",
        "specific objectives",
        "individual objectives",
      ],
      answer: "fundamental objectives",
      answerConfidence: "confirmed",
      explanation:
        "Strategic objectives sit in the system of objectives as **fundamental** (long-term, whole-org) objectives.",
      source: "Past exam Q5",
    },
    {
      id: "management-q-6",
      type: "mcq",
      topic: "foundations",
      difficulty: "medium",
      prompt: "Management as a practical activity is defined as:",
      options: [
        "the person or group of persons exercising the management functions (the decision center)",
        "the ensemble of accumulated knowledge transmitted via the educational system (the discipline)",
        "exercising functions to define objectives and structures and to motivate human resources",
        "the study of management processes in order to discover concepts and methods (the science)",
        "carrying out the management process — allocating and utilizing resources so objectives are met under conditions of effectiveness and efficiency",
      ],
      answer:
        "carrying out the management process — allocating and utilizing resources so objectives are met under conditions of effectiveness and efficiency",
      answerConfidence: "confirmed",
      explanation:
        "The other options are the *other four* meanings of management (decision center, discipline, science). A classic “match the definition to the right meaning” item.",
      source: "Past exam Q6",
    },
    {
      id: "management-q-7",
      type: "mcq",
      topic: "foundations",
      difficulty: "medium",
      prompt: "The correct variant for the managerial functions of the modern company is:",
      options: [
        "forecasting, organizing, planning, motivation, commanding",
        "forecasting, research and development, coordination, production",
        "forecasting (planning), organizing, coordination, motivation / commanding, control",
        "forecasting, motivating, coordination, decision, control-evaluating",
        "premonition, organizing, coordination, decision-training, evaluating",
      ],
      answer:
        "forecasting (planning), organizing, coordination, motivation / commanding, control",
      answerConfidence: "confirmed",
      explanation:
        "The five functions. Distractors insert non-functions (R&D, production, decision, “premonition”) or duplicate planning + forecasting.",
      source: "Past exam Q7",
    },
    {
      id: "management-q-8",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt:
        "Among the requirements a managerial decision must meet to maximize efficiency is **NOT**:",
      options: [
        "scientifically founded",
        "adopted by legally empowered persons",
        "aligned with the organizational culture values",
        "formulated clearly and concisely",
        "opportune (timely)",
      ],
      answer: "aligned with the organizational culture values",
      answerConfidence: "confirmed",
      explanation:
        "The six requirements do **not** include “aligned with organizational culture values” — it is the intruder (a NOT-type item).",
      source: "Past exam Q8",
    },
    {
      id: "management-q-9",
      type: "mcq",
      topic: "foundations",
      difficulty: "medium",
      prompt: "Management as a science represents the study of management processes within:",
      options: [
        "economic organizations",
        "organizations without an economic purpose",
        "companies",
        "public organizations",
        "organizations of any nature",
      ],
      answer: "organizations of any nature",
      answerConfidence: "confirmed",
      explanation:
        "The key phrase of the definition is **“organizations of any nature/kind.”** Every other option wrongly narrows the scope.",
      source: "Past exam Q9",
    },
    {
      id: "management-q-10",
      type: "mcq",
      topic: "foundations",
      difficulty: "easy",
      prompt:
        "Measuring obtained results, comparing them with forecasted objectives, determining deviations and adopting corrective measures represents:",
      options: ["forecasting", "organizing", "coordinating", "leading / motivating", "controlling"],
      answer: "controlling",
      answerConfidence: "confirmed",
      explanation: "Textbook wording of the **controlling** function.",
      source: "Past exam Q10",
    },
    {
      id: "management-q-11",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt: "Among the **primary factors** of the managerial decision is:",
      options: [
        "the environment",
        "the decisional variants",
        "the decisional criteria",
        "the decisional process",
        "the internal environment of the organization",
      ],
      answer: "the environment",
      answerConfidence: "confirmed",
      explanation:
        "The two primary factors are the **decision-maker** and **the environment**. Trap: “internal environment” alone is not the factor — the environment is internal **and** external.",
      source: "Past exam Q11",
    },
    {
      id: "management-q-12",
      type: "mcq",
      topic: "decision",
      difficulty: "hard",
      prompt: "For a decision to be scientifically founded it must:",
      options: [
        "use rigorous analysis and consecrated procedures, accounting for the decision-maker's experience",
        "apply modern techniques without completely excluding routine elements",
        "be based on scientific and realistic analysis methods, consider economic laws, adequately use data-processing techniques, and eliminate routine, subjectivism and improvisation",
        "be efficient even if the process implies certain elements of improvisation",
        "optimize results by respecting general principles and adapting to the external environment",
      ],
      answer:
        "be based on scientific and realistic analysis methods, consider economic laws, adequately use data-processing techniques, and eliminate routine, subjectivism and improvisation",
      answerConfidence: "confirmed",
      explanation:
        "Verbatim definition. The wrong options deliberately **re-admit routine/improvisation** or drift off-definition.",
      source: "Past exam Q12",
    },
    {
      id: "management-q-13",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "The main formalization document of the **processual** organization is:",
      options: [
        "the Gantt chart",
        "the process diagram",
        "the organizational chart",
        "the job description",
        "the procedure",
      ],
      answer: "the procedure",
      answerConfidence: "confirmed",
      explanation:
        "The **procedure** formalizes processual organization. Trap: the **organizational chart** is the main document of **structural** organization.",
      source: "Past exam Q13",
    },
    {
      id: "management-q-14",
      type: "mcq",
      topic: "strategy",
      difficulty: "hard",
      prompt: "The major components of the organization's strategy are:",
      options: [
        "vision, strategic objectives, hierarchy, modalities of action, resources, competitive advantage",
        "vision, mission, strategic objectives, organizational structure, hierarchical level, strategic modalities of action, resources, deadlines, competitive advantage",
        "vision, strategic objectives, hierarchical level, strategic modalities of action, resources, deadlines, competitive advantage",
        "vision, mission, strategic objectives, strategic modalities of action, resources, deadlines, competitive advantage",
        "mission, strategic objectives, strategic modalities of action, resources, deadlines, competitive advantage",
      ],
      answer:
        "vision, mission, strategic objectives, strategic modalities of action, resources, deadlines, competitive advantage",
      answerConfidence: "confirmed",
      explanation:
        "The 7 components exactly. Distractors insert non-components (hierarchy, organizational structure, hierarchical level) or drop one (the last omits vision).",
      source: "Past exam Q14",
    },
    {
      id: "management-q-15",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "The hierarchical span (span of control) represents:",
      options: [
        "the primary entity of structural organization",
        "the totality of positions directly subordinated to a manager",
        "the entities situated at the same distance from the top of the structure",
        "the entity formed by several workplaces under one management position",
        "the best-known, most-formalized form of organization",
      ],
      answer: "the totality of positions directly subordinated to a manager",
      answerConfidence: "confirmed",
      explanation:
        "Distractors are the definitions of *neighboring* concepts (job, hierarchical level, compartment, structural organization). Recommended span: 5–10.",
      source: "Past exam Q15",
    },
    {
      id: "management-q-16",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt: "For a management decision to be **opportune** it must:",
      options: [
        "capitalize on opportunities from the SWOT analysis",
        "fit into the optimal period for elaboration and operationalization",
        "be correlated with previous and later decisions",
        "be adopted by persons with legal empowerment",
        "be adopted considering the economic laws",
      ],
      answer: "fit into the optimal period for elaboration and operationalization",
      answerConfidence: "confirmed",
      explanation:
        "“Opportune/timely” = the optimal timeframe. The distractors map to the *other* requirements (correlation, authority, scientifically founded). Trap: SWOT-opportunities ≠ a decision being *opportune*.",
      source: "Past exam Q16",
    },
    {
      id: "management-q-17",
      type: "mcq",
      topic: "entrepreneurship",
      difficulty: "medium",
      prompt: "For a non-VAT-paying company, VAT is **not**:",
      options: [
        "deductible",
        "a tax that cannot be applied to its goods/services value",
        "an eligible expense in some financing programs",
        "a tax not paid to the State Budget",
        "a cost",
      ],
      answer: "deductible",
      answerConfidence: "confirmed",
      explanation:
        "A non-VAT firm cannot **deduct** VAT. For it, VAT *is* a cost, *is* eligible in some grants, and *is not* remitted to the budget — so the one thing it is **not** is deductible.",
      source: "Past exam Q17",
    },
    {
      id: "management-q-18",
      type: "mcq",
      topic: "strategy",
      difficulty: "medium",
      prompt: "“Changes in consumer preferences” would represent, in a SWOT analysis:",
      options: [
        "a strength",
        "a strength or a weakness",
        "a threat",
        "an opportunity or a threat",
        "an opportunity",
      ],
      answer: "an opportunity or a threat",
      answerConfidence: "confirmed",
      explanation:
        "It is an **external** factor → an opportunity or a threat (strengths/weaknesses are internal). Whether it helps or hurts depends on the firm.",
      source: "Past exam Q18",
    },
    {
      id: "management-q-19",
      type: "mcq",
      topic: "decision",
      difficulty: "easy",
      prompt: "According to the time horizon, managerial decisions are classified into:",
      options: [
        "operational, tactical and strategic",
        "under certainty, risk and uncertainty",
        "anticipated and unpredictable",
        "unicriterial and multicriterial",
        "unique, periodic and aleatory",
      ],
      answer: "operational, tactical and strategic",
      answerConfidence: "confirmed",
      explanation:
        "The distractors are the *other* classification criteria (environment knowledge, anticipation, criteria count, frequency).",
      source: "Past exam Q19",
    },
    {
      id: "management-q-20",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "The types of organizational relationships defined by the structural organization are:",
      options: [
        "functional, operational",
        "authority, cooperation, control",
        "coordination, execution, control",
        "coordination, control",
        "economic, financial, of influence",
      ],
      answer: "authority, cooperation, control",
      answerConfidence: "confirmed",
      explanation:
        "The three relation types. Trap: functional/operational are *compartment* categories, not relation types.",
      source: "Past exam Q20",
    },
    {
      id: "management-q-21",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "easy",
      prompt:
        "Depending on the specific tasks distributed, two categories of departments are distinguished:",
      options: [
        "structural and processual",
        "coordinating and subordinate",
        "functional and operational",
        "strategic and tactical",
        "administrative and auxiliary",
      ],
      answer: "functional and operational",
      answerConfidence: "confirmed",
      explanation:
        "Functional compartments support core activities; operational compartments directly achieve the org's purpose.",
      source: "Past exam Q21",
    },
    {
      id: "management-q-22",
      type: "mcq",
      topic: "strategy",
      difficulty: "medium",
      prompt: "Key success factors represent:",
      options: [
        "the ensemble of chances offered by the competitive environment",
        "the elements based on which a true and prior competition takes place among competitors",
        "the totality of economic/technical/social factors influencing the organization",
        "the system of values and aspirations of those who decide",
        "the general directions of action for achieving objectives",
      ],
      answer:
        "the elements based on which a true and prior competition takes place among competitors",
      answerConfidence: "confirmed",
      explanation:
        "Distractors are definitions of *opportunities*, the *environment*, decision-makers' values, and *strategic means of action*.",
      source: "Past exam Q22",
    },
    {
      id: "management-q-23",
      type: "mcq",
      topic: "hr",
      difficulty: "easy",
      prompt: "The most common method of human resource selection is:",
      options: [
        "the aptitude test",
        "the interview",
        "the curriculum vitae",
        "the letter of intent",
        "the candidate's file",
      ],
      answer: "the interview",
      answerConfidence: "confirmed",
      explanation: "The interview is the most common (and most criticized) selection method.",
      source: "Past exam Q23",
    },
    {
      id: "management-q-24",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt: "Which of the following decisions represents a strategic decision?",
      options: [
        "programming the work shifts for the Client Service department next month",
        "launching a massive advertising campaign for one product",
        "withdrawing from a non-profitable sector of activity",
        "choosing a new technology for optimizing the production process",
        "provisioning raw materials for the following week",
      ],
      answer: "withdrawing from a non-profitable sector of activity",
      answerConfidence: "confirmed",
      explanation:
        "Strategic = long-term, whole-organization, hard to reverse. Withdrawing from a sector reshapes the org's scope; the others are tactical/operational.",
      source: "Past exam Q24",
    },
    {
      id: "management-q-25",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "Circle the statement you consider true:",
      options: [
        "“increasing turnover by 10%” is a SMART objective",
        "“reducing costs in the next quarter” is a SMART objective",
        "“increasing profit by 20%” is not a SMART objective",
        "“attracting students to the theater” is a SMART objective",
      ],
      answer: "“increasing turnover by 10%” is a SMART objective",
      answerConfidence: "confirmed",
      explanation:
        "“Increase turnover by 10%” is specific & measurable (the course treats it as SMART). The others lack a measurable target or are vague.",
      source: "Past exam Q25",
    },
    {
      id: "management-q-26",
      type: "mcq",
      topic: "foundations",
      difficulty: "hard",
      prompt: "Which of the following phrases refers to management **as a practical activity**?",
      options: [
        "waste management",
        "time management",
        "sales management",
        "top-level management",
        "risk management",
        "wildlife management",
      ],
      answer: "sales management",
      answerConfidence: "attempt-selected",
      explanation:
        "**Working answer (await official key):** *sales management* = managing a function inside an organization (the practical activity). The item is weak — *time/risk/waste/wildlife management* also read as “managing something,” and *top-level management* denotes the decision-center meaning. Defer to the official key if it differs.",
      source: "Past exam Q26 (interpretive — reference §7C)",
    },
    {
      id: "management-q-27",
      type: "multi",
      topic: "mgmt-system",
      difficulty: "hard",
      prompt:
        "Which of the following statements about **SMART objectives** are true? (Select all that apply.)",
      options: [
        "“Increasing turnover by 10%” is a SMART objective",
        "SMART objectives are not accessible",
        "“Attracting students to the theater” is a SMART objective",
        "“Reducing costs in the next quarter” is a SMART objective",
        "SMART objectives are temporal (time-bound)",
        "“Hiring five more programmers” is a SMART objective",
      ],
      answer: [
        "“Increasing turnover by 10%” is a SMART objective",
        "SMART objectives are temporal (time-bound)",
      ],
      answerConfidence: "likely",
      explanation:
        "**a** true (specific & measurable) and **e** true (the **T** = Time-bound). **b** false (the **A** = Achievable/accessible); **c**, **d** false (not measurable/time-bound). **f** (“hiring five programmers”) is borderline — no explicit horizon — and awaits the official key (reference §7C).",
      source: "Past exam Q27 (partly interpretive)",
    },
    {
      id: "management-q-28",
      type: "multi",
      topic: "calc-utility-electre",
      difficulty: "hard",
      prompt: `A decision under certainty is analysed with the **global utility** and **ELECTRE** methods. Utility matrix (criteria C1–C5, weights **K**):

| | C1 | C2 | C3 | C4 | C5 |
|---|---|---|---|---|---|
| V1 | 0 | 1 | 0 | 1 | 0 |
| V2 | 0.8 | 0.6 | 0.2 | 0.8 | 0.6 |
| V3 | 1 | 0.7 | 0.4 | 0.1 | 0.3 |
| V4 | 0.5 | 0.9 | 0.7 | 0.5 | 1 |
| V5 | 0.5 | 0 | 1 | 0 | 0.4 |
| **K** | 0.12 | 0.15 | 0.30 | 0.23 | 0.20 |

Which statements are true? (Select all that apply.)`,
      options: [
        "the global utility of V1 is 0.450",
        "by global utility, the best variant is V2",
        "the concordance indicator between V1 and V4 is 0.38",
        "the global utility of V4 is 0.575",
        "by global utility, the best variant is V4",
        "the concordance indicator between V2 and V5 is 0.55",
      ],
      answer: [
        "the concordance indicator between V1 and V4 is 0.38",
        "by global utility, the best variant is V4",
      ],
      answerConfidence: "confirmed",
      explanation:
        "Global utilities = Σ(U×K): V1 **0.38**, V2 0.55, V3 0.428, V4 **0.72** (best), V5 0.44 — so (a) and (d) are false and (b) false. Concordance C(Ag,Ah)=Σ K where U(Ag)≥U(Ah): C(V1,V4)=0.15+0.23=**0.38** (true); C(V2,V5)=0.12+0.15+0.23+0.20=**0.70**, not 0.55 (f false).",
      source: "Past exam Q28",
    },
    {
      id: "management-q-29",
      type: "mcq",
      topic: "calc-vat",
      difficulty: "medium",
      prompt:
        "For a laptop with a final price of 3,902 lei, the VAT value is (standard rate 21% [VOLATILE]):",
      options: ["819.42 lei", "623 lei", "3,160.62 lei", "390.2 lei", "3,000 lei", "677.2 lei"],
      answer: "677.2 lei",
      answerConfidence: "confirmed",
      explanation:
        "$V = F/(1+r)\\times r = 3{,}902/1.21\\times 0.21 = 677.21$ lei. **Trap (819.42)** = $3{,}902\\times 0.21$, treating the final price as the base — the classic VAT mistake.",
      source: "Past exam Q29",
    },
    {
      id: "management-q-30",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt:
        "Which of the following objectives does **not** belong to the category of **specific** objectives?",
      options: [
        "response time ≤ 30 s for 80% of an online store's customers",
        "calling at least 200 customers by the end of the work schedule",
        "increasing net profit by 10% in the next year",
        "reducing file processing time by 0.8% in the current month",
        "ensuring a 99% compliance rate of issued payment documents",
      ],
      answer: "increasing net profit by 10% in the next year",
      answerConfidence: "confirmed",
      explanation:
        "Specific objectives are operational and short-term (days/weeks/months). “Increase net profit by 10% next year” spans a year and targets a top-level result → **fundamental**, not specific (a NOT-type item).",
      source: "Past exam Q30",
    },
    {
      id: "management-q-31",
      type: "mcq",
      topic: "foundations",
      difficulty: "hard",
      prompt: "Circle the correct statement:",
      options: [
        "the teacher can be the students' manager because he exercises all management functions",
        "the teacher cannot be their manager because he lacks formal authority over them",
        "the teacher can be their manager because he exercises the control function",
        "the teacher cannot be their manager because he does not exercise all management functions in relation to them",
        "the teacher cannot be their manager because he does not exercise the coordination function",
      ],
      answer:
        "the teacher cannot be their manager because he does not exercise all management functions in relation to them",
      answerConfidence: "likely",
      explanation:
        "**Working answer (await official key):** a manager exercises **all five** functions based on **formal authority**, and the teacher doesn't exercise the full set toward students. Option **b** is defensible too (whether a teacher holds formal authority over students is arguable). Reference §7C.",
      source: "Past exam Q31 (interpretive)",
    },
    {
      id: "management-q-32",
      type: "mcq",
      topic: "calc-salary",
      difficulty: "medium",
      prompt:
        "For a gross salary of 5,770 lei, the **complete** salary (total employer cost) would be (CAM 2.25% [VOLATILE]):",
      options: ["3,439 lei", "6,000 lei", "5,950 lei", "7,000 lei", "5,900 lei"],
      answer: "5,900 lei",
      answerConfidence: "confirmed",
      explanation:
        "Complete = gross + CAM(2.25%) = $5{,}770 + 5{,}770\\times 0.0225 = 5{,}770 + 129.83 \\approx 5{,}900$. **Trap (3,439)** = the *net* salary, a different concept.",
      source: "Past exam Q32",
    },
    {
      id: "management-q-33",
      type: "mcq",
      topic: "calc-cpm",
      difficulty: "hard",
      prompt:
        "By CPM, the estimated duration of an activity with work volume 100 h, daily production norm 8 h, 3 workers, and 69% norm fulfilment is:",
      options: ["5 days", "10 days", "7 days", "8 days", "4 days", "37 days", "6 days", "20 days", "1,656 days", "2,000 days"],
      answer: "6 days",
      answerConfidence: "confirmed",
      explanation:
        "$d = Q/(N_p\\times N_m\\times p_i) = 100/(8\\times 3\\times 0.69) = 6.04 \\approx 6$ days. **Traps:** 4 = forgetting the 0.69; 1,656 / 2,000 = multiplying instead of dividing.",
      source: "Past exam Q33",
    },

    // ===== New practice — single-correct (practice_questions.md §A) =========
    {
      id: "management-q-pq1",
      type: "mcq",
      topic: "foundations",
      difficulty: "easy",
      prompt: "Which of the following is **NOT** one of the five meanings of “management”?",
      options: ["science", "art", "decision center", "practical activity", "execution process"],
      answer: "execution process",
      answerConfidence: "confirmed",
      explanation:
        "The five meanings are science / art / discipline of study / practical activity / decision center. “Execution process” is the *other* category of work process, not a meaning of management.",
      source: "Practice PQ1",
    },
    {
      id: "management-q-pq2",
      type: "mcq",
      topic: "foundations",
      difficulty: "easy",
      prompt: "The basis of the **commanding** function is:",
      options: ["communication", "motivation", "authority", "control", "planning"],
      answer: "motivation",
      answerConfidence: "confirmed",
      explanation: "Commanding rests on **motivation**. Trap: communication is the basis of *coordinating*.",
      source: "Practice PQ2",
    },
    {
      id: "management-q-pq3",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt:
        "A decision adopted **with the approval of the decision-maker's hierarchical superior** is classified as:",
      options: ["integral", "approved", "periodic", "strategic", "unicriterial"],
      answer: "approved",
      answerConfidence: "confirmed",
      explanation:
        "Classification by *decision-making competence*: integral (no approval needed) vs **approved**.",
      source: "Practice PQ3",
    },
    {
      id: "management-q-pq4",
      type: "mcq",
      topic: "decision",
      difficulty: "medium",
      prompt: "Which method is used for decisions under **risk**?",
      options: [
        "ELECTRE",
        "global utility",
        "decision tree / mathematical expectancy",
        "Hurwicz",
        "Laplace",
      ],
      answer: "decision tree / mathematical expectancy",
      answerConfidence: "confirmed",
      explanation:
        "ELECTRE & global utility = certainty; Hurwicz & Laplace = uncertainty; the decision tree (mathematical expectancy) = **risk**.",
      source: "Practice PQ4",
    },
    {
      id: "management-q-pq5",
      type: "mcq",
      topic: "strategy",
      difficulty: "medium",
      prompt: "The bargaining power of **customers** increases when:",
      options: [
        "customers buy small quantities",
        "products are highly differentiated",
        "the products are standardized / hardly differentiated",
        "transfer costs are high",
        "the sector's product strongly influences the quality of the customer's product",
      ],
      answer: "the products are standardized / hardly differentiated",
      answerConfidence: "confirmed",
      explanation:
        "Standardized products → customers switch easily → more power. Differentiation, high transfer costs and strong quality influence all *reduce* customer power.",
      source: "Practice PQ5",
    },
    {
      id: "management-q-pq6",
      type: "mcq",
      topic: "strategy",
      difficulty: "easy",
      prompt: "A **distinctive competence** is:",
      options: [
        "an external opportunity",
        "a particular or exclusive skill/resource in which the organization excels",
        "an environmental threat",
        "a key success factor possessed by all competitors",
        "a strategic means of action",
      ],
      answer: "a particular or exclusive skill/resource in which the organization excels",
      answerConfidence: "confirmed",
      explanation: "A distinctive competence is what the organization does better/uniquely vs rivals.",
      source: "Practice PQ6",
    },
    {
      id: "management-q-pq7",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "The **primary unit of process-based organization** is:",
      options: ["the activity", "the attribution", "the task", "the job", "the compartment"],
      answer: "the task",
      answerConfidence: "confirmed",
      explanation:
        "Task = primary unit of *processual* organization. Trap: the **job** is the primary unit of *structural* organization.",
      source: "Practice PQ7",
    },
    {
      id: "management-q-pq8",
      type: "mcq",
      topic: "mgmt-system",
      difficulty: "medium",
      prompt: "A KPI obtained as the ratio between an **effect** indicator and an **effort** indicator is a(n):",
      options: [
        "effectiveness indicator",
        "efficiency indicator",
        "fundamental objective",
        "specific objective",
        "individual objective",
      ],
      answer: "efficiency indicator",
      answerConfidence: "confirmed",
      explanation: "Efficiency = effect/effort (productivity, ROI). Effectiveness = achieved/expected.",
      source: "Practice PQ8",
    },
    {
      id: "management-q-pq9",
      type: "mcq",
      topic: "projects",
      difficulty: "medium",
      prompt: "A **fictional (dummy) activity** in a network diagram:",
      options: [
        "consumes time but no resources",
        "consumes resources but no time",
        "consumes neither time nor resources but conditions the start of successor activities",
        "is always on the critical path",
        "is a work package",
      ],
      answer:
        "consumes neither time nor resources but conditions the start of successor activities",
      answerConfidence: "confirmed",
      explanation: "A dummy activity only expresses a precedence constraint.",
      source: "Practice PQ9",
    },
    {
      id: "management-q-pq10",
      type: "mcq",
      topic: "projects",
      difficulty: "easy",
      prompt: "The **“sacred cow”** project-selection method is:",
      options: [
        "numerical, based on NPV",
        "numerical, based on IRR",
        "non-numerical — the project is suggested by an important person in the organization",
        "the checklist method",
        "the payback term",
      ],
      answer:
        "non-numerical — the project is suggested by an important person in the organization",
      answerConfidence: "confirmed",
      explanation: "“Sacred cow” is a *non-numerical* selection method.",
      source: "Practice PQ10",
    },
    {
      id: "management-q-pq11",
      type: "mcq",
      topic: "hr",
      difficulty: "easy",
      prompt: "The **halo effect** is a disadvantage of:",
      options: ["the interview", "aptitude tests", "the evaluation sheet", "recruitment", "the polygraph"],
      answer: "the evaluation sheet",
      answerConfidence: "confirmed",
      explanation: "The halo effect = a score on one factor biasing the rating of another.",
      source: "Practice PQ11",
    },
    {
      id: "management-q-pq12",
      type: "mcq",
      topic: "hr",
      difficulty: "easy",
      prompt: "Which conflict-handling style is the **“win-win”** approach?",
      options: ["competing", "compromising", "accommodating", "collaborating", "avoiding"],
      answer: "collaborating",
      answerConfidence: "confirmed",
      explanation: "Collaborating = win-win. Competing = win-lose; compromising = lose-lose.",
      source: "Practice PQ12",
    },
    {
      id: "management-q-pq13",
      type: "mcq",
      topic: "entrepreneurship",
      difficulty: "easy",
      prompt: "For a **VAT-registered** enterprise, deducting VAT on purchases:",
      options: [
        "increases the VAT owed",
        "decreases the VAT to be paid to the State Budget",
        "has no effect",
        "is illegal",
        "applies only to exports",
      ],
      answer: "decreases the VAT to be paid to the State Budget",
      answerConfidence: "confirmed",
      explanation: "A VAT payer offsets input VAT against output VAT, lowering the amount remitted.",
      source: "Practice PQ13",
    },
    {
      id: "management-q-pq14",
      type: "mcq",
      topic: "foundations",
      difficulty: "easy",
      prompt: "“Whatever the definition, management means primarily the ___ of other people.”",
      options: ["control", "coordination", "supervision", "motivation", "selection"],
      answer: "coordination",
      answerConfidence: "confirmed",
      explanation: "Management primarily means the **coordination** of other people.",
      source: "Practice PQ14",
    },

    // ===== New practice — multi-correct (practice_questions.md §B) ==========
    {
      id: "management-q-pq15",
      type: "multi",
      topic: "decision",
      difficulty: "hard",
      prompt:
        "Which statements are **requirements of an efficient managerial decision**? (Select all that apply.)",
      options: [
        "be opportune (timely)",
        "be adopted by persons with legal empowerment",
        "include routine and improvisation",
        "be formulated clearly and concisely",
        "maximize the number of decisional alternatives",
        "be correlated with previous and future decisions",
      ],
      answer: [
        "be opportune (timely)",
        "be adopted by persons with legal empowerment",
        "be formulated clearly and concisely",
        "be correlated with previous and future decisions",
      ],
      answerConfidence: "confirmed",
      explanation:
        "Routine/improvisation must be **eliminated** (not included), and “maximize the number of alternatives” is not a requirement.",
      source: "Practice PQ15",
    },
    {
      id: "management-q-pq16",
      type: "multi",
      topic: "strategy",
      difficulty: "hard",
      prompt: "Which statements about **SWOT** are true? (Select all that apply.)",
      options: [
        "Strengths and weaknesses are internal factors",
        "The analysis always starts with the internal environment",
        "In the WT quadrant, the choice is to give up the non-performing segment",
        "Opportunities are largely uncontrollable by the organization",
        "The SO quadrant calls for a defensive / exit strategy",
      ],
      answer: [
        "Strengths and weaknesses are internal factors",
        "In the WT quadrant, the choice is to give up the non-performing segment",
        "Opportunities are largely uncontrollable by the organization",
      ],
      answerConfidence: "confirmed",
      explanation:
        "SWOT starts with the **external** environment (not internal), and the **SO** quadrant calls for growth/development (not exit) — those two statements are false.",
      source: "Practice PQ16",
    },
    {
      id: "management-q-pq17",
      type: "multi",
      topic: "mgmt-system",
      difficulty: "hard",
      prompt: "Which statements are true? (Select all that apply.)",
      options: [
        "The job is the primary unit of structural organization",
        "The task is the primary unit of process-based organization",
        "Strategic objectives appear in the system of objectives as individual objectives",
        "Specific objectives have an operational character and short horizons",
        "The recommended span of control is 5–10",
      ],
      answer: [
        "The job is the primary unit of structural organization",
        "The task is the primary unit of process-based organization",
        "Specific objectives have an operational character and short horizons",
        "The recommended span of control is 5–10",
      ],
      answerConfidence: "confirmed",
      explanation:
        "Strategic objectives appear as **fundamental** objectives (not individual) — that statement is false.",
      source: "Practice PQ17",
    },
    {
      id: "management-q-pq18",
      type: "multi",
      topic: "hr",
      difficulty: "hard",
      prompt: "Which statements about **motivation** are true? (Select all that apply.)",
      options: [
        "Intrinsic motivation arises from the work content itself",
        "Negative motivation relies on the threat of sanctions",
        "For Herzberg, hygiene factors are the ones that motivate",
        "Maslow's needs tend to be satisfied bottom-up",
        "Alderfer's ERG model has five need groups",
      ],
      answer: [
        "Intrinsic motivation arises from the work content itself",
        "Negative motivation relies on the threat of sanctions",
        "Maslow's needs tend to be satisfied bottom-up",
      ],
      answerConfidence: "confirmed",
      explanation:
        "For Herzberg, **motivators** drive motivation (hygiene only prevents dissatisfaction), and ERG has **three** need groups (Existence, Relatedness, Growth) — both false.",
      source: "Practice PQ18",
    },

    // ===== Calculation items rendered as MCQs (practice_questions.md §C) ====
    {
      id: "management-q-calc1",
      type: "mcq",
      topic: "calc-vat",
      difficulty: "medium",
      prompt: "A product's final price is 2,178 RON. The VAT value is (rate 21% [VOLATILE]):",
      options: ["457.38 RON", "378 RON", "1,800 RON", "217.8 RON", "360 RON"],
      answer: "378 RON",
      answerConfidence: "confirmed",
      explanation:
        "$V = 2{,}178/1.21\\times 0.21 = 1{,}800\\times 0.21 = 378$; base = 1,800. **Trap (457.38)** = $2{,}178\\times 0.21$ (VAT on the final price instead of the base).",
      source: "Practice CALC1",
    },
    {
      id: "management-q-calc3",
      type: "mcq",
      topic: "calc-salary",
      difficulty: "medium",
      prompt: "Gross salary 6,200 RON. The complete salary (total employer cost) is (CAM 2.25% [VOLATILE]):",
      options: ["6,339.5 RON", "6,200 RON", "6,540 RON", "6,061 RON", "4,030 RON"],
      answer: "6,339.5 RON",
      answerConfidence: "confirmed",
      explanation:
        "$CAM = 6{,}200\\times 0.0225 = 139.5$; complete = $6{,}200 + 139.5 = 6{,}339.5$. **Trap (4,030)** ≈ the *net* salary.",
      source: "Practice CALC3",
    },
    {
      id: "management-q-calc4",
      type: "mcq",
      topic: "calc-salary",
      difficulty: "hard",
      prompt:
        "Gross salary 5,000 RON, personal deduction 0. The net salary is (CAS 25%, CASS 10%, tax 10% [VOLATILE]):",
      options: ["2,925 RON", "3,250 RON", "3,500 RON", "2,600 RON", "3,150 RON"],
      answer: "2,925 RON",
      answerConfidence: "confirmed",
      explanation:
        "CAS 1,250; CASS 500; taxable = 5,000 − 1,250 − 500 = 3,250; tax = 325; net = 5,000 − 1,250 − 500 − 325 = **2,925**. **Trap (3,250)** = the taxable base (forgetting income tax).",
      source: "Practice CALC4",
    },
    {
      id: "management-q-calc5",
      type: "mcq",
      topic: "calc-cpm",
      difficulty: "medium",
      prompt:
        "By CPM: work volume 240 h, daily norm 8 h, 2 workers, 75% norm fulfilment. The duration is:",
      options: ["15 days", "20 days", "30 days", "16 days", "40 days"],
      answer: "20 days",
      answerConfidence: "confirmed",
      explanation:
        "$d = 240/(8\\times 2\\times 0.75) = 240/12 = 20$. **Trap (15)** = $240/(8\\times 2)$ (dropping the norm-fulfilment %).",
      source: "Practice CALC5",
    },
    {
      id: "management-q-calc11",
      type: "mcq",
      topic: "calc-sme",
      difficulty: "medium",
      prompt:
        "A firm has 45 employees, turnover €12M, total assets €5M. Its category is ([VOLATILE] thresholds):",
      options: [
        "micro-enterprise",
        "small enterprise",
        "medium-sized enterprise",
        "large enterprise (not an SME)",
      ],
      answer: "small enterprise",
      answerConfidence: "confirmed",
      explanation:
        "45 < 50 → small band. Small thresholds: ≤ €10M turnover **OR** ≤ €43M assets. Turnover €12M exceeds €10M, **but** assets €5M ≤ €43M → the OR is satisfied → **small**. **Trap:** declaring it “not small” because turnover > €10M (ignoring the turnover-OR-assets rule).",
      source: "Practice CALC11",
    },
  ],
};
